# Generated by Django 4.1.7 on 2023-03-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='vehicle_description',
            field=models.CharField(max_length=30),
        ),
    ]
