# Generated by Django 4.1.7 on 2023-03-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_vehiclemodel_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='vehicle_type',
            field=models.CharField(choices=[('Two Wheeler', 'Two Wheeler'), ('Three Wheeler', 'Three Wheeler'), ('Four Wheeler', 'Four Wheeler')], max_length=25),
        ),
    ]
